### ISSUE TITLE
Add graphs for Django?

### ISSUE THREAD

**Issue by aaugustin** [erikbern/git-of-theseus#13]
I was curious what they would look like so I generated them. This takes a bit of time; adding them to the pics/ directory will save others a few hours of CPU time.
![stack_plot](https://cloud.githubusercontent.com/assets/788910/20976956/6a9ed712-bca4-11e6-8f0f-5d72b639b038.png)
![survival_plot](https://cloud.githubusercontent.com/assets/788910/20976955/6a9d25ac-bca4-11e6-95d2-fdbefea1ea05.png)

**Comment by erikbern** [comment]
cool!
