### ISSUE TITLE
Organize code by version (tag) rather than year

### ISSUE THREAD

**Issue by remram44** [erikbern/git-of-theseus#15]
Seeing the lifetime of code introduced in a given version would be useful.

**Comment by erikbern** [comment]
what do you mean with version? from git tags?

sure feel free to send a PR :)

**Comment by remram44** [comment]
Yes, basically all the code added between tag A and B would be shown as changes "from version B", in the same way you currently show "from year YYYY". I can probably add this when I get the time.
