### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'c'

### ISSUE THREAD

**Issue by comradealain** [erikbern/git-of-theseus#17]
I am getting IOError hile executing `python stack_plot.py cohorts.json`

Error trace:
```
Traceback (most recent call last):
  File "stack_plot.py", line 10, in <module>
    data = json.load(open(args.inputs[0]))
IOError: [Errno 2] No such file or directory: 'c'
```

The error was resolved after I changed `args.inputs[0]` to `args.inputs`. I noticed that `args.inputs` was changed to `args.inputs[0]` in 080fd67 after #7 was reported. I checked the documentation for python2.7 and ran the following snippet:

```
import argparse
parser = argparse.ArgumentParser(description='Sample')
parser.add_argument('inputs')
args = parser.parse_args()
print args.inputs, type(args.inputs)
```

When I ran `python sample.py sample` it printed `sample <type 'str'>` on stdout. It seems `args.inputs` still returns a **string**.

**Comment by Ullaakut** [comment]
Yep, changing `args.inputs[0]` into `args.input` actually makes it work fine.

**Comment by meeDamian** [comment]
@Ullaakut Changing it into `args.inputs` *

**Comment by erikbern** [comment]
sorry fixing it in #18
