### ISSUE TITLE
clarification about survival plots

### ISSUE THREAD

**Issue by monperrus** [erikbern/git-of-theseus#25]
Those visualizations are awesome. I have questions about the survival plots. The legend says `%of commits still present over time`. Is it the full commit? Or the percentage of lines?

Also, about the "over time", does it mean:

* % of commits present at least n years?
* % of commits present exactly n years?
* or something else?

**Comment by erikbern** [comment]
It explains the number of lines still present after n years. I'll put a clarification in the readme

**Comment by monperrus** [comment]
my survival plot is not strictly decreasing, how is this possible?
![survival_plot](https://cloud.githubusercontent.com/assets/803666/21578186/42e101e2-cf77-11e6-8bc8-f58852237ee9.png)

**Comment by erikbern** [comment]
see clarification in readme
