### ISSUE TITLE
multiple repositories for stack_plot

### ISSUE THREAD

**Issue by engel75** [erikbern/git-of-theseus#34]
Hi there,

I would like to analyze http://git.openstack.org. Is it possible to add multiple repository support for stack_plot as well?

All the best,
Flo

**Comment by erikbern** [comment]
probably possible, nothing i've thought about though :)

**Comment by engel75** [comment]
Hi Erik,

so the question is - how to motivate you coding that? ;)

Any Idea? ;)

All the best,
Flo

**Comment by erikbern** [comment]
haha not going to do that but feel free to do it yourself
