### ISSUE TITLE
Multi-repo

### ISSUE THREAD

**Issue by Stibbons** [erikbern/git-of-theseus#4]
Hello

I really like the visualization generated by this project! Is it possible to support several git repository instead of just one?

Thanks
Gaetan

**Comment by erikbern** [comment]
you have to run `python analyze.py` separately for each project and store the data in separate directories using the `--outdir` flag. Then you can run `python survival_plot.py <foo/survival.json> <bar/survival.json>` etc

**Comment by erikbern** [comment]
will add it to readme
