### ISSUE TITLE
git-of-theseus-stack-plot --help crashes

### ISSUE THREAD

**Issue by requiel20** [erikbern/git-of-theseus#40]
> requiel@requiels-PC ~/gitRepo/vscode $ git-of-theseus-stack-plot --help
> Traceback (most recent call last):
>   File "/home/requiel/.virtualenvs/git-theseus/bin/git-of-theseus-stack-plot", line 3, in <module>
>     stack_plot()
>   File "/home/requiel/.virtualenvs/git-theseus/local/lib/python2.7/site-packages/git_of_theseus/stack_plot.py", line 42, in stack_plot
>     args = parser.parse_args()
>   File "/usr/lib/python2.7/argparse.py", line 1701, in parse_args
>     args, argv = self.parse_known_args(args, namespace)
>   File "/usr/lib/python2.7/argparse.py", line 1733, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/usr/lib/python2.7/argparse.py", line 1939, in _parse_known_args
>     start_index = consume_optional(start_index)
>   File "/usr/lib/python2.7/argparse.py", line 1879, in consume_optional
>     take_action(action, args, option_string)
>   File "/usr/lib/python2.7/argparse.py", line 1807, in take_action
>     action(self, namespace, argument_values, option_string)
>   File "/usr/lib/python2.7/argparse.py", line 996, in __call__
>     parser.print_help()
>   File "/usr/lib/python2.7/argparse.py", line 2340, in print_help
>     self._print_message(self.format_help(), file)
>   File "/usr/lib/python2.7/argparse.py", line 2314, in format_help
>     return formatter.format_help()
>   File "/usr/lib/python2.7/argparse.py", line 281, in format_help
>     help = self._root_section.format_help()
>   File "/usr/lib/python2.7/argparse.py", line 211, in format_help
>     func(*args)
>   File "/usr/lib/python2.7/argparse.py", line 211, in format_help
>     func(*args)
>   File "/usr/lib/python2.7/argparse.py", line 517, in _format_action
>     help_text = self._expand_help(action)
>   File "/usr/lib/python2.7/argparse.py", line 603, in _expand_help
>     return self._get_help_string(action) % params
> ValueError: incomplete format
> 

Some information about which options each command takes should be added to the readme too maybe

**Comment by erikbern** [comment]
Lol that’s unfortunate. Let me fix
