### ISSUE TITLE
Automatically determine default branch if not specified

### ISSUE THREAD

**Issue by ArneBachmann** [erikbern/git-of-theseus#59]
We have a case of a repo with no `master` branch, but another branch is marked and checked out by default.
In case I don't use the `--branch <name>` option for `analyze`, I get an error which is hard to understand at first:
`stderr: 'fatal: bad revision 'master'`.

One option would be to display a warning and simply use the default branch instead.

**Comment by MFreidank** [comment]
I submitted one because I ran into the same issue today. #63
