### ISSUE TITLE
how repo param works?

### ISSUE THREAD

**Issue by murphygithub** [erikbern/git-of-theseus#62]
I have tried below and failed. Seems it can only take local repo as param?
C:\Users\Administrator>git-of-theseus-analyze https://github.com/erikbern/git-of
-theseus
it throw 
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\git_of_theseus\analyze.py", line 185, in analyze_cmdline
    analyze(**kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\git_of_theseus\analyze.py", line 30, in analyze
    repo = git.Repo(repo)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-p
ackages\git\repo\base.py", line 124, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: C:\Users\Administrator\https:\github.com\erikbern\git-o
f-theseus

what to do if I am trying to anaysis github repo?

**Comment by erikbern** [comment]
the argument is supposed to be a local file path, not an URL

can clone the repo first
