### ISSUE TITLE
stack_plot.py: TypeError

### ISSUE THREAD

**Issue by pushcx** [erikbern/git-of-theseus#7]
I was following on the readme, but `python stack_plot.py cohorts.json` gave me an error after the previous command succeeded:
```
/home/pushcx/.virtualenvs/git-of-theseus/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Traceback (most recent call last):
  File "stack_plot.py", line 10, in <module>
    data = json.load(open(args.inputs))
TypeError: invalid file: ['cohorts.json']
```

Playing with it, the result of `args.inputs` is an array when `open` wants a `str`. I'm not familiar with `argparse` and I can't see how this code would ever have worked, unless perhaps it's a python 3/2 incompatibility. Maybe you wants `args.inputs[0]`, but more likely there's something going on I don't understand.

Wonderful blog post, btw, and I really appreciate that you made this code available so I can play with it on a few repos. Thanks!

**Comment by erikbern** [comment]
This was probably introduced in #5 

will fix

**Comment by erikbern** [comment]
should be fixed now, can you try again?

**Comment by erikbern** [comment]
relevant commit: 080fd67bd5179a779eab254d7f227d2c50d88505

**Comment by pushcx** [comment]
Yes, it worked. Thanks!

FWIW, though `stack_plot.png` was correctly produced, I also got a warning:
```
$ python stack_plot.py cohorts.json
/home/pushcx/.virtualenvs/git-of-theseus/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
```
