### ISSUE TITLE
Released version 0.3.0 has no git tag

### ISSUE THREAD

**Issue by miketheman** [erikbern/git-of-theseus#80]
https://pypi.org/project/git-of-theseus/0.3.0/ appears to have been released on Nov 10, 2021, but there's no associated tag pointing to that release: https://github.com/erikbern/git-of-theseus/tags

The lack of a tag makes determining what changes have been applied to the codebase between versions and since the last release.
I presume it's after this commit: 75c49c6813a2451b1abb48a0767c694bad0b1a30 - would you mind making a tag for that?

**Comment by erikbern** [comment]
I'm sorry, what's the concern here? You can easily go and look at the history of setup.py and see that it was bumped here: https://github.com/erikbern/git-of-theseus/commit/cf4332d0a524e36881e7cbc93a6a4ade00736992 – it's super easy to find.

closing this for now, but happy to reopen if you can clarify if this is causing any problems etc!
