### ISSUE TITLE
Drop Python 3.6 build and add Python 3.11

### ISSUE THREAD

**Issue by owenlamont** [erikbern/git-of-theseus#86]
I noticed a build for [Python 3.6 ](https://github.com/erikbern/git-of-theseus/actions/runs/4154236286/jobs/7186471912) failed here. Since [Python 3.6 is past end of life](https://devguide.python.org/versions/) I think it is reasonable to drop it. I've also tested git-of-theseus manually with no issues on Python 3.11 if we wanted to add that.

**Comment by erikbern** [comment]
Yeah that would make sense! I think it's as easy as just updating https://github.com/erikbern/git-of-theseus/blob/master/.github/workflows/ci-cd.yml
