### ISSUE TITLE
Cumulated statics on multi-repo environement

### ISSUE THREAD

**Issue by GPuigRenart** [erikbern/git-of-theseus#88]
we are working in a multi-repo environment. Is there a way to cumulate graphs apart from survival? Cohorts will be the most interesting for me

**Comment by erikbern** [comment]
There's PR here that I realized has been sitting there for a while. Let me see what I can do to get it merged: https://github.com/erikbern/git-of-theseus/pull/70

**Comment by AlexanderWillner** [comment]
As #70 has not been merged, this issue is not really closed, is it?
